project_id = "rbtjfzhfryieoduoyeqk"

[functions.verify-submission]
verify_jwt = false

[functions.create-job]
verify_jwt = false

[functions.process-job]
verify_jwt = false
 
 [functions.send-completion-email]
 verify_jwt = false
